import "./globals.css";
import Navigation from "@/components/Navigation";
import Header from "@/components/Header";
import { Metadata } from "next";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-inter antialiased">
        <Header />

        <div className="max-w-[2800px] w-full px-20 mx-auto mt-10">
          <NextTopLoader />
          <div className="mt-10">{children}</div>
        </div>
      </body>
    </html>
  );
}
