import Footer from "@/components/Footer";
import "./globals.css";
import Header from "@/components/Header";
import { Metadata } from "next";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-inter antialiased h-full min-h-screen">
        <Header />

        <div className="max-w-[2800px] w-full px-20 mx-auto mt-10  flex flex-col flex-grow">
          <NextTopLoader
            color="#2563eb" // Tailwind blue-600
            initialPosition={0.08}
            crawlSpeed={200}
            height={3}
            crawl={true}
            showSpinner={false}
            easing="ease"
            speed={200}
            shadow="0 0 10px #2563eb,0 0 5px #2563eb"
          />
          <div className="mt-10 h-full flex-grow">{children}</div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
